# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20a2070b1bb64286fe4797f06ad338892690c83dc40798ee92f4152e5cb20ba8ac113327c61bf699ac552f1f0f36e921dcd7563a64e4a74e3e318ceefde8fe61

test:
  secret_key_base: 939f0558dbe1cc37ff058e2b1c5e2c5e69a3107f81c054497d0832a2cbfae1b6ee721ddacd16f37b36c97b6daa87f65c0b054d20c795de935335fa394ba25501

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
